image: maven:3.6.1-jdk-8-slim

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  ZIP_NAME: jpenc-converter.zip

stages:
  - build
  - test
  - package
  - publish

cache:
  paths:
    - .m2/repository/
    - target/
  key:
    "$CI_COMMIT_SHA"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: on_failure
    expire_in: 30 days
    paths:
      - log
      - target/surefire-reports

package:
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends zip && rm -rf /var/lib/apt/lists/*
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS package  -DskipTests
    - cp target/jpencconverter-*.jar .
    - cp src/main/resources/application.properties application.properties.sample
    - zip -r $ZIP_NAME jpencconverter-*.jar application.properties.sample README.md
  artifacts:
    expire_in: 3 days
    paths:
      - target/*.jar
      - $ZIP_NAME


publish:
  stage: publish
  image: curlimages/curl
  rules:
    - if: '$CI_COMMIT_TAG && $GITLAB_ACCESS_TOKEN'
  script:
    - curl --header "PRIVATE-TOKEN:$GITLAB_ACCESS_TOKEN" --upload-file $ZIP_NAME "$CI_API_V4_URL/projects/${CI_PROJECT_ID}/packages/generic/jpencconverter/$CI_COMMIT_TAG/$ZIP_NAME"
